from scoreboard import scoreboard

match1 = scoreboard('Tim Garuda', 'Tim Elang')
print('10" - Garuda Gol')
match1.up1()
print('40" - Elang Gol')
match1.up2()
print('70" - Elang Gol')
match1.up2()
print('70" - Gol Elang dianulir')
match1.down2()
print('87" - Garuda Gol')
match1.up1()
s1, s2 = match1.peek1(), match1.peek2()
print(f'Full Time : Garuda {s1} - {s2} Elang')
